version: "3.6"
services:
  db-dev:
    build:
      context: .
      dockerfile: docker/db.dockerfile
    ports:
      - "3366:3306"
    secrets:
      - mysql_root_password
      - mysql_password
    environment:
      MYSQL_ROOT_PASSWORD_FILE: /run/secrets/mysql_root_password
      MYSQL_DATABASE: yga
      MYSQL_USER: yga
      MYSQL_PASSWORD_FILE: /run/secrets/mysql_password
    volumes:
      - db-dev:/var/lib/mysql
  flask-dev:
    build:
      context: .
      dockerfile: docker/flask.dockerfile
    depends_on:
      - db-dev
    restart: on-failure
    tmpfs:
      - /run
    secrets:
      - mysql_password
      - flask_key
    volumes:
      - depot-dev:/var/depot

  nginx-dev:
    build:
      context: .
      dockerfile: docker/nginx.dockerfile
    depends_on:
      - flask-dev
    ports:
      - "10086:8086"
    volumes:
      - depot-dev:/var/depot

volumes:
  db-dev:
  depot-dev:

secrets:
  mysql_password:
    file: ./secrets/mysql_password
  mysql_root_password:
    file: ./secrets/mysql_root_password
  flask_key:
    file: ./secrets/flask_key