version: "3.6"
services:
  db-dev:
    networks:
      dev:
        aliases:
          - db
    build:
      context: .
      dockerfile: docker/db.dockerfile
    ports:
      - "30366:3306"
    secrets:
      - mysql_root_password
      - mysql_password
    environment:
      MYSQL_ROOT_PASSWORD_FILE: /run/secrets/mysql_root_password
      MYSQL_DATABASE: yga
      MYSQL_USER: yga
      MYSQL_PASSWORD_FILE: /run/secrets/mysql_password
    tmpfs:
      - /var/lib/mysql

  flask-dev:
    networks:
      dev:
        aliases:
          - flask
    build:
      context: .
      dockerfile: docker/flask.dockerfile
    depends_on:
      - db-dev
    restart: on-failure
    secrets:
      - mysql_password
      - flask_key
    tmpfs:
      - /var/depot

  nginx-dev:
    networks:
      - dev
    build:
      context: .
      dockerfile: docker/nginx.dockerfile
    depends_on:
      - flask-dev
    ports:
      - "10086:8086"
    tmpfs:
      - /var/depot

secrets:
  mysql_password:
    file: ./secrets/mysql_password
  mysql_root_password:
    file: ./secrets/mysql_root_password
  flask_key:
    file: ./secrets/flask_key

networks:
  dev: