name: docker-compose main
on: 
  push:
    branches:
      - main

jobs:
  compose:
    runs-on: [self-hosted, linux]
    steps:
      - name: checkout
        uses: actions/checkout@v3
      
      - name: write secrets
        run: |
          echo ${{secrets.FLASK_KEY}} > secrets/flask_key
          echo ${{secrets.MYSQL_PASSWORD}} > secrets/mysql_password
          echo ${{secrets.MYSQL_ROOT_PASSWORD}} > secrets/mysql_root_password

      - name: compose
        run: docker-compose up